### ISSUE TITLE
リクエストパラメータ無しのRPCが作れない

### ISSUE THREAD

**Issue by ttynsmr** [ttynsmr/potato#20]
❌作れない
```yaml
# yaml -> torikime -> generate .proto & rpc code.
contracts:
  diagnosis:
    sever_sessions:
      request:
      response:
        session_count: int32
```

⭕作れる
```yaml
# yaml -> torikime -> generate .proto & rpc code.
contracts:
  diagnosis:
    sever_sessions:
      request:
        x: int32 # 不要なパラメータを足す
      response:
        session_count: int32
```
