### ISSUE TITLE
マップの作成方法を決める

### ISSUE THREAD

**Issue by ttynsmr** [ttynsmr/potato#72]
- [ ] tilemapに3Dオブジェクトを配置
- [ ] tilemapに2Dスプライトを配置

```yaml
area:
  id: 1
  map: map_001.yaml
```

```yaml
map:
  size:
    width: 5 # x
    height: 5 # y
    depth: 5 # z
  offset:
    x: -2
    y: 0
    z: -2
  defines:
    - name: wall
      movable: False
    - name: floor
      movable: True
    - name: undefined
    - name: door1
      goto_area: 1
    - name: door2
      goto_area: 3
  tiles:
    - [0,0,0,0,0]
    - [0,1,1,1,0]
    - [4,1,1,1,3]
    - [0,1,1,1,0]
    - [0,0,0,0,0]
```
